// Generated by Supabase (`generate_typescript_types`) for project `executagent`.
// Regenerate after schema changes; do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      artifacts: {
        Row: {
          content_type: string
          created_at: string
          environmental_report: Json | null
          id: string
          metadata: Json
          quality_score: number | null
          sha256: string
          signature: string
          storage_path: string
          task_id: string
          user_id: string
          variation_index: number
        }
        Insert: {
          content_type?: string
          created_at?: string
          environmental_report?: Json | null
          id?: string
          metadata?: Json
          quality_score?: number | null
          sha256: string
          signature: string
          storage_path: string
          task_id: string
          user_id: string
          variation_index: number
        }
        Update: {
          content_type?: string
          created_at?: string
          environmental_report?: Json | null
          id?: string
          metadata?: Json
          quality_score?: number | null
          sha256?: string
          signature?: string
          storage_path?: string
          task_id?: string
          user_id?: string
          variation_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "artifacts_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          role: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          role?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      routing_embeddings: {
        Row: {
          content: string
          created_at: string
          embedding: string
          id: string
          kind: string
          skill_slug: string
        }
        Insert: {
          content: string
          created_at?: string
          embedding: string
          id?: string
          kind?: string
          skill_slug: string
        }
        Update: {
          content?: string
          created_at?: string
          embedding?: string
          id?: string
          kind?: string
          skill_slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "routing_embeddings_skill_slug_fkey"
            columns: ["skill_slug"]
            isOneToOne: false
            referencedRelation: "skills"
            referencedColumns: ["slug"]
          },
        ]
      }
      skills: {
        Row: {
          created_at: string
          default_tier: Database["public"]["Enums"]["tier"]
          description: string
          entrypoint: string
          id: string
          manifest: Json
          name: string
          slug: string
          status: Database["public"]["Enums"]["skill_status"]
          version: string
        }
        Insert: {
          created_at?: string
          default_tier?: Database["public"]["Enums"]["tier"]
          description: string
          entrypoint: string
          id?: string
          manifest?: Json
          name: string
          slug: string
          status?: Database["public"]["Enums"]["skill_status"]
          version?: string
        }
        Update: {
          created_at?: string
          default_tier?: Database["public"]["Enums"]["tier"]
          description?: string
          entrypoint?: string
          id?: string
          manifest?: Json
          name?: string
          slug?: string
          status?: Database["public"]["Enums"]["skill_status"]
          version?: string
        }
        Relationships: []
      }
      task_events: {
        Row: {
          created_at: string
          id: number
          payload: Json
          task_id: string
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          payload?: Json
          task_id: string
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: never
          payload?: Json
          task_id?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_events_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          created_at: string
          deleted_at: string | null
          error: string | null
          id: string
          preferences: Json
          prompt: string
          routing: Json | null
          skill_slug: string | null
          status: Database["public"]["Enums"]["task_status"]
          tier: Database["public"]["Enums"]["tier"]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          error?: string | null
          id?: string
          preferences?: Json
          prompt: string
          routing?: Json | null
          skill_slug?: string | null
          status?: Database["public"]["Enums"]["task_status"]
          tier?: Database["public"]["Enums"]["tier"]
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          error?: string | null
          id?: string
          preferences?: Json
          prompt?: string
          routing?: Json | null
          skill_slug?: string | null
          status?: Database["public"]["Enums"]["task_status"]
          tier?: Database["public"]["Enums"]["tier"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_skill_slug_fkey"
            columns: ["skill_slug"]
            isOneToOne: false
            referencedRelation: "skills"
            referencedColumns: ["slug"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      skill_status: "active" | "deprecated"
      task_status:
        | "queued"
        | "routing"
        | "generating"
        | "validating"
        | "completed"
        | "failed"
        | "cancelled"
      tier: "S" | "M" | "L"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
